export const mockLaunchesAPIData = [
    {
        flight_number: 99,
        mission_name: 'Starlink-9 (v1.0) & BlackSky Global 5-6',
        mission_id: [],
        launch_year: '2020',
        launch_date_unix: 1596777120,
        launch_date_utc: '2020-08-07T05:12:00.000Z',
        launch_date_local: '2020-08-07T01:12:00-04:00',
        is_tentative: false,
        tentative_max_precision: 'hour',
        tbd: false,
        launch_window: null,
        rocket: {
          rocket_id: 'falcon9',
          rocket_name: 'Falcon 9',
          rocket_type: 'FT',
          first_stage: [],
          second_stage: [],
          fairings: []
        },
        ships: [ 'GOMSCHIEF', 'GOMSTREE', 'OCISLY' ],
        telemetry: { flight_club: null },
        launch_site: {
          site_id: 'ksc_lc_39a',
          site_name: 'KSC LC 39A',
          site_name_long: 'Kennedy Space Center Historic Launch Complex 39A'
        },
        launch_success: true,
        links: {
          mission_patch: '',
          mission_patch_small: '',
          reddit_campaign: '',
          reddit_launch: '',
          reddit_recovery: '',
          reddit_media: '',
          presskit: null,
          article_link: '',
          wikipedia: '',
          video_link: '',
          youtube_id: '',
          flickr_images: []
        },
        details: 'This mission will launch the ninth batch of operational Starlink satellites, which are expected to be version 1.0, from LC-39A, Kennedy Space Center. It is the tenth Starlink launch overall. The satellites will be delivered to low Earth orbit and will spend a few weeks maneuvering to their operational altitude of 550 km. This mission is includes a rideshare of two BlackSky satellites on top of the Starlink stack. The booster for this mission is expected to land an ASDS.',
        upcoming: false,
        static_fire_date_utc: '2020-06-24T18:18:00.000Z',
        static_fire_date_unix: 1593022680,
        timeline: null,
        crew: null,
        last_date_update: '2020-08-04T02:33:44.000Z',
        last_ll_launch_date: null,
        last_ll_update: null,
        last_wiki_launch_date: '2020-08-07T05:12:00.000Z',
        last_wiki_revision: 'ea423e3d-d5fa-11ea-ad99-0e82730e990d',
        last_wiki_update: '2020-08-04T02:33:44.000Z',
        launch_date_source: 'wiki'
      },
      {
        flight_number: 100,
        mission_name: 'Starlink-10 (v1.0) & SkySat 19-21',
        mission_id: [],
        launch_year: '2020',
        launch_date_unix: 1597761060,
        launch_date_utc: '2020-08-18T14:31:00.000Z',
        launch_date_local: '2020-08-18T10:31:00-04:00',
        is_tentative: false,
        tentative_max_precision: 'hour',
        tbd: false,
        launch_window: 0,
        rocket: {
          rocket_id: 'falcon9',
          rocket_name: 'Falcon 9',
          rocket_type: 'FT',
          first_stage: [],
          second_stage: [],
          fairings: []
        },
        ships: [ 'GOMSTREE', 'GOMSCHIEF', 'OCISLY', 'GOQUEST' ],
        telemetry: { flight_club: null },
        launch_site: {
          site_id: 'ccafs_slc_40',
          site_name: 'CCAFS SLC 40',
          site_name_long: 'Cape Canaveral Air Force Station Space Launch Complex 40'
        },
        launch_success: true,
        links: {
          mission_patch: '',
          mission_patch_small: '',
          reddit_campaign: '',
          reddit_launch: '',
          reddit_recovery: '',
          reddit_media: '',
          presskit: null,
          article_link: '',
          wikipedia: '',
          video_link: '',
          youtube_id: '',
          flickr_images: []
        },
        details: 'This mission will launch the tenth batch of operational Starlink satellites, which are expected to be version 1.0, from LC-39A, Kennedy Space Center. It is the eleventh Starlink launch overall. The satellites will be delivered to low Earth orbit and will spend a few weeks maneuvering to their operational altitude of 550 km. This mission is includes rideshare payloads, SkySats 19-21, on top of the Starlink stack. The booster for this mission is expected to land on an ASDS.',
        upcoming: false,
        static_fire_date_utc: null,
        static_fire_date_unix: null,
        timeline: null,
        crew: null,
        last_date_update: '2020-08-15T02:21:25.000Z',
        last_ll_launch_date: null,
        last_ll_update: null,
        last_wiki_launch_date: '2020-08-18T14:31:00.000Z',
        last_wiki_revision: '042bcead-de9e-11ea-b6d9-0e010ab9f931',
        last_wiki_update: '2020-08-15T02:21:25.000Z',
        launch_date_source: 'wiki'
      },
]

export const mockedMappedLaunchData = [
    {
        flightNumber: 9,
        launchYear: "2019",
        missionName: "Global 5-6",
        rocketName: "Falcon 9",
    },
    {
        flightNumber: 12,
        launchYear: "2020",
        missionName: "Starlink-10 ",
        rocketName: "Falcon 8",
    },
    {
        flightNumber: 99,
        launchYear: "2020",
        missionName: "BlackSky Global 5-6",
        rocketName: "Falcon 1",
    },
    {
        flightNumber: 67,
        launchYear: "2007",
        missionName: "Mission-test-1",
        rocketName: "Falcon 2",
    },
]